### ISSUE TITLE
homework review completed, 請調整

### ISSUE THREAD

**Issue by hatelove** [MorrisChan/TDDHomework_Day1#1]
上課中一直強調，測試案例那11筆 product 的資料，沒有循序關係，請不要用 loop 來產生測試資料。

請調整測試案例，用測試案例來描述需求，來當作規格。

測試案例應該要清楚地描述與看到那11筆資料的意義與資訊。

**Comment by MorrisChan** [comment]
感謝91哥，測試案例已調整。 #1
